#ifndef COMPILER_H
# define COMPILER_H

// Here we will store all the data generated by the compilation
// We will have a list with the instructions generated
// NOTE: I will not store all instructions here and then print them
// in a file. My intention is to only store instructions here that
// cannot be outputed into a file bc changes can be yet done

# include "linked_list.h"
# include <stdio.h>

extern t_list *instructions;

// Maybe also store here a reference to the output file??
extern FILE *c3a_output;

// Number of lines the compiled has. Used when printing instructions
extern int line;
extern int instructions_inputed;

extern int current_reg;
extern int regs_reserved;

// Prints all the instructions into c3a_output.
void	print_all_instructions();
void	add_instruction(char *instruction, int position);

char	open_output_file(char *file);
void	close_output_file();

void	end_compilation();

t_list	*create_list(int position);
t_list	*join_list(t_list **first, t_list *second);
void	fill_list(t_list *list, int goto_position);

#endif
